name: ESLint
on:
  pull_request:
    branches:
      - main
jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: |
          npm install -g eslint
          eslint -v
          eslint 'src/index.js'
